services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  prestashop:
    image: prestashop/prestashop:8.1
    container_name: prestashop
    restart: always
    ports:
      - "80:80"
    environment:
      DB_SERVER: mysql
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWD: ${MYSQL_PASSWORD}
      PS_DEV_MODE: "1"
      PS_INSTALL_AUTO: "0"
      PS_DOMAIN: "116.203.138.177"
      PS_SSL_ENABLED: "0"
    depends_on:
      - mysql
    volumes:
      - prestashop_data:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
    restart: always

volumes:
  db_data: