<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLMwmUUH\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLMwmUUH/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerLMwmUUH.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerLMwmUUH\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerLMwmUUH\appAppKernelProdContainer([
    'container.build_hash' => 'LMwmUUH',
    'container.build_id' => '72a11924',
    'container.build_time' => 1746301880,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLMwmUUH');
