<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhjIYvLKAnE3YOybY/3Gr'."\n".'lVF5/utrAj4pFgIvkBBfDqxz6jbaU0rpaqHPVSdTd6UHcVffnd8V0cspjqkkPM4k'."\n".'asf0mTnMVbcOGOY4WME5oj8Ie8XGSjOPWfAuDI0SwklOwbSqp8NQXmVOKBIkG6kU'."\n".'Eqgouo78KVpfVfrCRHj1vfp8FY9KBj0VHNyzYDa0clma1AMbo/ful7fcy7GbALC6'."\n".'D9jE579jfiBL3VZQ4qvnNBa6J93OuWpLhu2bYp2oRGU8QcesHxGzBhIsx5m51Euz'."\n".'nCaFggYg2YtcD5vfSC0ir6Zlfqw1zSicpZW+A2NwD/qs20tYgxyqpyOT4ibhuiVZ'."\n".'2wIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
