<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTfxfkjK\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTfxfkjK/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTfxfkjK.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTfxfkjK\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerTfxfkjK\appAppKernelDevDebugContainer([
    'container.build_hash' => 'TfxfkjK',
    'container.build_id' => '70148857',
    'container.build_time' => 1746305462,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTfxfkjK');
